server:
  port: 8080
spring:
  application:
    name: Task manager
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  profiles:
    default: "prod"
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
# swagger-ui custom path
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  cache:
    disabled: true
