server:
  port: 8080
spring:
  application:
    name: Task manager
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  profiles:
    default: "dev"