spring:
  datasource:
    url: jdbc:h2:mem:project99;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  jpa:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.web: debug
    org.springframework.security: warn
    org.hibernate: debug
debug: true