spring:
  datasource:
    url: jdbc:h2:mem:project99;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  jpa:
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      #schema-locations:
      #data-locations: classpath:resources/data.sql
logging:
  level:
    org.springframework.web: warn
    org.springframework.security: warn
    org.hibernate: debug
    org.springframework.test.context.jdbc: debug # Test init sql data
debug: true
